import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "@/components/mainHeader";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-slate-50"}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
