import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "@/components/mainHeader";


export const metadata: Metadata = {
  title: "Task List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-50">
      <MainHeader />
        {children}
      </body>
    </html>
  );
}