import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const geistInter = Inter({
  variable: "--font-geist-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Task List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistInter.variable}`}
      >
        {children}
      </body>
    </html>
  );
}